[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 1000000
via_ir = true

# Apenas as dependências NECESSÁRIAS para swaps
remappings = [
    "@uniswap/v4-core/=lib/v4-core/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"